sudo: false
language: node_js

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email:
    on_failure: change

node_js:
  - '7.7'

install:
  - npm install

script:
  - npm run build.prod
  - npm run test
  - nrm run test:mocha
